// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC74i4aZAvrpoFMBQoXNzvAkBTbT8ggXFI',
    appId: '1:989408006299:web:ddba7a07e633cb8d9e363e',
    messagingSenderId: '989408006299',
    projectId: 'ejercimente-b02ab',
    authDomain: 'ejercimente-b02ab.firebaseapp.com',
    storageBucket: 'ejercimente-b02ab.appspot.com',
    measurementId: 'G-8H8TVW2DF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjzRixO2Q4QZJyY-6hiH-XphjdqW69lKw',
    appId: '1:989408006299:android:d0388dde2c7403f99e363e',
    messagingSenderId: '989408006299',
    projectId: 'ejercimente-b02ab',
    storageBucket: 'ejercimente-b02ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA6S17U_8S4Da1kTJcuPGA4iPhS7LoEcM',
    appId: '1:989408006299:ios:f0abe1a5dae2b8c69e363e',
    messagingSenderId: '989408006299',
    projectId: 'ejercimente-b02ab',
    storageBucket: 'ejercimente-b02ab.appspot.com',
    iosBundleId: 'com.alejandro.ejercimente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA6S17U_8S4Da1kTJcuPGA4iPhS7LoEcM',
    appId: '1:989408006299:ios:a81d207d5a96e4a29e363e',
    messagingSenderId: '989408006299',
    projectId: 'ejercimente-b02ab',
    storageBucket: 'ejercimente-b02ab.appspot.com',
    iosBundleId: 'com.alejandro.ejercimente.RunnerTests',
  );
}
